import vpex
import triton
import triton_vsi_backend

from backend_utils import VendorInfoBase  # noqa: E402

vendor_info = VendorInfoBase(
    vendor_name="VeriSilicon", device_name="vsi", device_query_cmd=""
)

CUSTOMIZED_UNUSED_OPS = (
            "cat",
            "pad",
            "constant_pad_nd",
            "cummin",
            "native_dropout",
            "embedding",
            "exponential_",
            "gelu",
            "native_group_norm",
            "_weight_norm_interface",
            "_weight_norm",
            "instance_norm",
            "isfinite",
            "isin.Tensor_Tensor",
            "isin.Scalar_Tensor",
            "isin.Tensor_Scalar",
            "isinf",
            "isnan",
            "minimum",
            "maximum",
            "native_layer_norm",
            "rand",
            "randn",
            "rand_like",
            "randn_like",
            "resolve_neg",
            "normal.Tensor_float",
            "normal.float_Tensor",
            "normal.Tensor_Tensor",
            "uniform_",
            "mean.dim",
            "mm",
            "multinomial",
            "pow.Scalar",
            "pow.Tensor_Scalar",
            "pow.Tensor_Tensor",
            "relu",
            "rsqrt",
            "sigmoid",
            "silu",
            "softmax.int",
            "sort",
            "triu",
            "topk",
            "var_mean.correction",
            "linalg_vector_norm",
            "where.self_out",
            "where.self",
            "where.ScalarSelf",
            "where.ScalarOther",
            "max.dim",
            "min.dim",
            "argmax",
            "scaled_dot_product_attention",
            "log_softmax.int",
            "outer",
            "cross_entropy_loss",
            "scatter.reduce",
            "gather",
            "isclose",
            "allclose",
            "flip",
            "slice_scatter",
            "select_scatter",
            "index_select",
            "tile",
            "_unique2",
            "_upsample_bicubic2d_aa",
            "upsample_nearest2d",
            "nonzero",
            "repeat",
            "masked_select",
            "hstack",
            "stack"
            "cat",
            "vstack",
            "repeat_interleave.Tensor",
            "randperm",
            "diag",
            "diag_embed",
            "diagonal_backward",
            "index_add",
            "count_nonzero",
            "polar",
            "kron",
            "index_put_",
            "index_put",
            "contiguous",
            "log_sigmoid",
            "mse_loss",
            "argmin",
            "batch_norm",
            "linspace",
            "log_softmax.int",
            "nll_loss_forward",
            "nll_loss_backward",
            "nll_loss2d_forward",
            "nll_loss2d_backward",
            "quantile",
            "nan_to_num",
            )


__all__ = ["*"]
